### ISSUE TITLE
./tool not working with clang on debian 9

### ISSUE THREAD

**Issue by npisanti** [hundredrabbits/Orca-c#1]
```console
./tool -c clang build release orca 
``` 
returns 
```
clang: error: unknown argument: '-no-pie'
```

also if you install the `clang-6.0` package and do
```console
./tool -c clang-6.0 build release orca 
``` 
it works as intended, so it is just matter of minimum clang version (default debian is 3.8 )

`make release` doesn't detect the gcc version but works as intended, so this bug isn't really a priority, but it's still good to know this behavior.

Thanks for the great work on the orca porting!

**Comment by cancel** [comment]
Thanks. Let me add some stuff to the build tool to only specify no-pie if the clang version is high enough.

**Comment by npisanti** [comment]
perfect!

**Comment by cancel** [comment]
Fixed by 8514233eaed06f20f395b958db597b5aa5f5c794

**Comment by cancel** [comment]
@npisanti could you describe the separate issue with gcc version not being detected? Is a warning message printed?

**Comment by npisanti** [comment]
```console
make release orca
```
returns 
```
Warning: Failed to detect compiler type
Warning: Failed to detect compiler version
```
but then compiles as usual

**Comment by cancel** [comment]
Thanks, I'll take a look at it. Which version of Debian are you using?

**Comment by npisanti** [comment]
Debian 9 (Stretch).
