### ISSUE TITLE
MIDI Velocity Differences between Orca-JS and Orca-C

### ISSUE THREAD

**Issue by juniorctl** [hundredrabbits/Orca-c#15]
Orca-JS and Orca-C send different velocity values when provided with the same arguments. This is most noticable when providing no velocity argument as Orca-JS sends a note-on with full velocity while Orca-C uses a velocity of 1 which is not audible. Below is a table of the velocity values generated from example commands:

```
Command     Orca-JS    Orca-C

:03C..      127        1 #
:03C0.      No event   1
:03C1.      8          15
:03C2.      16         29
:03C3.      25         43
:03C4.      33         57
:03C5.      42         71
:03C6.      50         85
:03C7.      59         99
:03C8.      67         113
:03C9.      76         127
:03Ca.      84         0
:03Cb.      93         2
:03Cc.      101        7
:03Cd.      110        12
:03Ce.      118        17
:03Cf.      127        22
:03C[g-z].  127        increases by 5 for each letter until z which is 122
```

**Comment by neauoire** [comment]
Which one do you prefer? 
I personally like the 16 steps `0-f` style.

**Comment by juniorctl** [comment]
I have no preference myself but I think that standardizing on the Orca-JS behavior would cause the least disruption as Orca-JS seems to have more users. The existing `examples/_midi.orca` file as well as the introductory YouTube video both have MIDI examples with a `.` as the velocity argument which could be confusing for users if they stopped making a sound.
