### ISSUE TITLE
GCC 4.9.2 flags errors on Debian Jessie/Oldstable (PocketCHIP)

### ISSUE THREAD

**Issue by ghostlevel** [hundredrabbits/Orca-c#3]
JIC:
I compiled Orca-c on my PocketCHIP yesterday out of curiosity, ARMv7l, Debian Jessie/oldstable, 
GCC 4.9.2
i had to remove the latest two cc_flags "-Werror=incompatible-pointer-types` -Werror=int-conversion" to be able to build orca & cli (not exactly sure of the consequences yet of course)

The GCC errors were:
>cc1: error: -Werror=incompatible-pointer-types: no option -Wincompatible-pointer-types
>cc1: error: -Werror=int-conversion: no option -Wint-conversion" 

// Also echoing #1 with the same two harmless GCC Warnings
>Warning: Failed to detect compiler type
>Warning: Failed to detect compiler version

(clang-3.8 on Jessie failed with some errors but i'm skipping clang for now as it's OldStable - the CHIPs/PocketCHIP are stuck on it for now...)

I also built Orca-c on macOS with no problem and tested it with Sonic-Pi as an OSC server (using the Plogue MIDI format) on the same machine but i haven't tested sending OSC from the PocketCHIP yet.

**Comment by cancel** [comment]
Thanks. This should be fixed now.
@npisanti this should also fix the compiler detection warnings from #1
