### ISSUE TITLE
"live help" missing

### ISSUE THREAD

**Issue by attejensen** [hundredrabbits/Orca-c#42]
The very useful "live help" display found in electron orca is solely missed :-)

Example: the midi operator (:)
Hovering over the ":" in electron orca displays "Midi" in lower part of the screen
Hovering over the first input (one east) displays "-chann", etc

**Comment by cancel** [comment]
This feature is a part of #29, so I've updated the title of #29 to include the name of the operator itself, instead of just the port names, and I'm closing this issue.
