### ISSUE TITLE
Overflow bug introduced by PR #45

### ISSUE THREAD

**Issue by cancel** [hundredrabbits/Orca-c#46]
https://github.com/hundredrabbits/Orca-c/pull/45/commits/906b114c7651088d24d6cdca32b7f13db9b8a4cc#diff-1619fa5fe6f90820b2758c463fbcf50cL1251

`Isz` is incorrect here. `int` is correct. `Isz` parameter can overflow and is not guarded correctly. This code should not have been changed and it is now unsafe. It should be reverted.

**Comment by cancel** [comment]
Also this line https://github.com/hundredrabbits/Orca-c/pull/45/commits/906b114c7651088d24d6cdca32b7f13db9b8a4cc#diff-1619fa5fe6f90820b2758c463fbcf50cL1262

And this line should be `int` not `Isz` for the step size
https://github.com/hundredrabbits/Orca-c/pull/45/commits/906b114c7651088d24d6cdca32b7f13db9b8a4cc#diff-1619fa5fe6f90820b2758c463fbcf50cR1281

If you want to use `Isz` instead of `int` for these step parameters you need to add a bunch more overflow checking code, and you will need to use the `size_t` and `ssize_t` min/max constants for tests to avoid warnings about implicit casts.

None of these are going to cause problems in practice, since we limit the grid size to a much smaller number elsewhere in the code, but there was no reason to change it to `Isz` when `int` was fine and already had the correct guarding logic.

**Comment by npisanti** [comment]
sorry it's my fault, i thought `Usz` and `Isz` should have been used as much as possible for portability, i will revert changes to those functions right now, in the future i will advice to use Usz` and `Isz` just in the `sim.c` file.

**Comment by randrew** [comment]
`int` is portable for this particular use case. `Isz` also works, but you have to change the code that does overflow checks, and it's going to be a bit trickier since `Isz` can be either 32-bit or 64-bit. In this case it was fine as `int` because we're only using it to apply small changes to the absolute coordinates, and it's in the "UI" layer.

**Comment by npisanti** [comment]
understood!
