### ISSUE TITLE
open file improvement, browse folder structure + tab completion

### ISSUE THREAD

**Issue by attejensen** [hundredrabbits/Orca-c#57]
Currently open file from the menu depends on the user being able to spell the exact filename + location. It would be nice to see what’s in the directory structure, tab completion would help as well…

**Comment by cancel** [comment]
A file manager is out of scope for this project, unless someone submits a fully working PR for it. The open file dialog supports `~` expansion, but live file tab completion and other such things such as file and structure listing would end up being more code than the entire rest of Orca-c, and would require lots of platform-specific code.

**Comment by neauoire** [comment]
Let me suggest something tho, use very simple filenames like [this](https://github.com/XXIIVV/Alicef/tree/master/enfer).
