### ISSUE TITLE
Paste from external source

### ISSUE THREAD

**Issue by a-atamian** [hundredrabbits/Orca-c#63]
With the JS version, I like the ability to have some blocks of code on a separate txt file and just copy/paste some of them in orca, however, it seems that this doesn't work with this version? 
I tried on windows with the cygwin version, using a debian in WSL and remotely from a RPI with Putty.

**Comment by neauoire** [comment]
It works on Elementary Linux using their default terminal. I think this issue might be on the terminal end.

**Comment by cancel** [comment]
Putty from Windows won't work with X clipboard manipulation. There's no way to do it. You will have to copy and paste normally like you would with normal terminal interaction.

I don't know about Debian WSL or how WSL works with X clipboard. Probably it doesn't.

For cygwin, you need to install xclip.
