### ISSUE TITLE
Noob Q: Bangs doesn't seams to trigger UDP events to Pilot

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [hundredrabbits/Orca-c#68]
Hi, I'm very new to ORCA and Pilot, seams I'm failing to send simple UDP messages from orca-c to Pilot.
There `;` doesn't light up when is next to `*`.

![image](https://user-images.githubusercontent.com/346914/92312750-b29d7900-ef78-11ea-817d-de9105b569d0.png)

I compile orca in a Ubuntu 20.04 laptop.

But the same configuration works perfectly if I tried it on the electron app

**Comment by npisanti** [comment]
hello, have you activated the OSC output in orca-c menu? that should also activate the UDP output

**Comment by patriciogonzalezvivo** [comment]
Thanks @npisanti, you where right I need to both enable OSC and change the port to `49161`. This means we need to choose between raw UDP strings and OSC protocol, right? Is like that by design?

**Comment by npisanti** [comment]
nope, the `;` character is for UDP, the `=` character is used for OSC, you can use both in the same orca file but they will be sent to the same destination.
