### ISSUE TITLE
not launching on Pop!_OS 21.04

### ISSUE THREAD

**Issue by insanerwayner** [hundredrabbits/Orca-c#78]
after building and executing:

```
zsh: illegal hardware instruction (core dumped)  build/orca
```

**Comment by npisanti** [comment]
i suspect the distro is not the problem, can you try changing `-march=nehalem` with `-march=native` in those lines of the `tool` file?

https://github.com/hundredrabbits/Orca-c/blob/master/tool#L323

**Comment by insanerwayner** [comment]
That worked!
