### ISSUE TITLE
Random operator ('R') doesn't respect capitalization

### ISSUE THREAD

**Issue by hsitz** [hundredrabbits/Orca-c#79]
The Random operator seems to work differently in Orca-c than regular Orca.  In regular Orca the Random ('R') operator's output will have the case (upper or lower) that matches that of the right operand:

 ```
  aRD 
   C
-or-
 aRd
  c
```

In Orca-c, however, the output of R seems to be always lowercase, regardless of the case of the input.

**Comment by npisanti** [comment]
Fixed now, thanks for reporting!
