### ISSUE TITLE
Question: Does it work with UDP/Pilot?

### ISSUE THREAD

**Issue by i3games** [hundredrabbits/Orca-c#80]
I'm on a Mac.

I compiled Orca-c via make. MIDI works, but Pilot stays silent.
 
Orca (Electron) works fine with Pilot out of the box.

**Comment by npisanti** [comment]
orca-c OSC output defaults to 49162, but it seems Pilot defaults listening to 49161, you have to access the orca-c menu with `CTRL+D` and go to `OSC Output ...` then `OSC Output Port ...` and set it to 49161

**Comment by i3games** [comment]
Ah, thank you! I thought UDP and OSC were separate things and had wondered why there was no configuration for the UDP port. It works.

**Comment by npisanti** [comment]
You're welcome! 

OSC messages are transmitted over UDP so it makes sense to have a single configuration for that. Closing this issue.
