### ISSUE TITLE
"mirror" repo ahead of "main" repo?

### ISSUE THREAD

**Issue by dacto** [hundredrabbits/Orca-c#83]
There are two orca-c repos according to: https://github.com/hundredrabbits/Orca-c/blob/d027a414d5ff257b52c613284673933077a53cfa/README.md?plain=1#L11-L13 
1. https://git.sr.ht/~rabbits/orca -> "main"
2. https://github.com/hundredrabbits/Orca-c -> "mirror"

I stumbled upon the bug about `random` not honoring capitalization in the "main" repo but found that it had been fixed already in the "mirror" repo (https://github.com/hundredrabbits/Orca-c/commit/bdb86c340669788f940247fb95c5e7db2bfc6803).

It seems that the mirror is ahead of the main repo by a number of commits.

Has the github hosted repo become the main repo?

**Comment by neauoire** [comment]
cc @cancel

**Comment by randrew** [comment]
It's up to @neauoire to update the Hundredrabbits sr.ht repo if changes are put into the GitHub repo. I don't have (or want) access to the one on sr.ht.

**Comment by neauoire** [comment]
Pulled the latest changes from the github repo, I'm not really comfortable handling two repos at once, sorry about the delay :)
