### ISSUE TITLE
No way to send CC above `35`

### ISSUE THREAD

**Issue by levibeach** [hundredrabbits/Orca-c#84]
Am I missing something or is there currently no way to send **CC** messages to anything over `35` in Orca-c? Looks like the JavaScript version starts at `64` but you can change the offset using `$cc:40`, however Orca-c doesn't have the `$` option. 🤔

**Comment by crcdng** [comment]
I just stumbled across this as well, can't enter `$` in orca-c / Mac.

**Comment by ivanvoid** [comment]
Same on linux Ubuntu 22.04

**Comment by npisanti** [comment]
By the way orca is designed only 36 values are available to select the midi CC, so no number higher than 35 can be reached. An hack you could use is to put a switch in the midi cc operator here:

https://github.com/hundredrabbits/Orca-c/blob/master/sim.c#L232

to remap the available numbers to other midi CCs, remapping them for to the parameters you want to automate.

**Comment by crcdng** [comment]
> By the way orca is designed only 36 values are available to select the midi CC, so no number higher than 35 can be reached. An hack you could use is to put a switch in the midi cc operator here:
> 
> https://github.com/hundredrabbits/Orca-c/blob/master/sim.c#L232
> 
> to remap the available numbers to other midi CCs, remapping them for to the parameters you want to automate.

In the JS Version we can use the Syntax 

```$cc:40..#pulse.colour.....#.```

to reach numbers over 36 for CC values. The problem that is addressed in this bug report is that in orca-c the "$" key does not work.

**Comment by npisanti** [comment]
Sorry, for now the `$` operator is not a feature available in orca-c.

**Comment by crcdng** [comment]
Maybe this could be mentioned prominently in the documentation, because without the possibility for Control Change and Program Change messages it is then rather unusable for anything MIDI.

**Comment by npisanti** [comment]
orca-c can send both the canonical bank select message (cc0) and program select message (cc32) so calling it "unusable" for MIDI seems a bit gratuitous, but i acknowledge that with a range of values of 0-35 for cc you have to get a bit more creative with the external devices to make them work inside the given limits.
